# Generated by Django 4.2.5 on 2023-09-17 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologist',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='contact',
            field=models.CharField(default='1234567890', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='country',
            field=models.CharField(default='Ghana', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='image',
            field=models.ImageField(blank=True, default='superuser\\static\\superuser\\media\\profile.png', upload_to='profile-uploads/'),
        ),
        migrations.AddField(
            model_name='cardiologist',
            name='town',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
