# Generated by Django 4.2.5 on 2023-09-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_cardiologist_address_cardiologist_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiologist',
            old_name='image',
            new_name='profile',
        ),
    ]
