# Generated by Django 4.2.5 on 2023-09-17 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_rename_image_cardiologist_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='contact',
            field=models.CharField(default='1234567890', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='Ghana', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, default='superuser\\static\\superuser\\media\\ekg.png', upload_to='logo-uploads/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='town',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
