# Generated by Django 4.2.5 on 2023-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_hospital_contact_hospital_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologist',
            name='profile',
            field=models.ImageField(blank=True, default='superuser/static/superuser/media/profile.png', upload_to='profile-uploads/'),
        ),
    ]
