# Generated by Django 4.2.5 on 2023-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0007_rename_available_credits_hospital_available_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='total_credits',
            new_name='slots_bought',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='invoice_no',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='reference',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
