# Generated by Django 4.2.5 on 2023-09-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_rename_total_credits_purchasehistory_slots_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superuser.hospital'),
        ),
    ]
