# Generated by Django 4.2.5 on 2023-09-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0009_alter_purchasehistory_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='cardiologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardiologist', to='superuser.cardiologist'),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital', to='superuser.hospital'),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cardio-uploads/'),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
