# Generated by Django 4.2.5 on 2023-09-19 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0013_rename_patient_reporthistory_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='superuser.reporthistory'),
        ),
    ]
